version: '3.8'

services:
  pgvector:
    image: pgvector/pgvector:pg15
    container_name: pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
#      POSTGRES_DB: dwh
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
